#!/bin/bash

myopen() {
	for arg in "$@"; do
		if [[ "$arg" == *"http"* ]]; then
			explorer.exe "$arg"
		else
			explorer.exe "$(wslpath -w "$arg")"
		fi
	done
}

source $DOTFILES/bin/libs/iswsl

if ! isWSL >/dev/null; then
	open $@
else
	myopen "$@"
fi
